# From SQL to Pandas Challenge 4

In [1]:
# import libraries
import pandas as pd

# load data
# This code is made to load our data stored on Google Drive
def gd_path(file_id):
    """Generate a shareable link from Google Drive file id."""
    return f"https://drive.google.com/uc?export=download&id={file_id}"

# Google Drive file ids
files_id = {
    "titles": "1PLdn50N9GRa53ZbuVWo0l47F_IXdvlEm",
    "sales": "1fzFc9rwYmVIPaGOFmhLVxCi3kg19vNU2",
    "publishers": "1s9E8_AVOziTrowb3wyh2jg3PV763VOyq",
    "employee": "1h9mUjsVqpP74b1w0x7KOw37n_n9Ulkt5",
    "authors": "1fEF89Nhe61EebAljKlwFwfEuokK0o6aJ"
}

# Read data from Google Drive
sales = pd.read_csv(gd_path(files_id["sales"]), sep=";")
authors = pd.read_csv(gd_path(files_id["authors"]), sep=";")
publishers = pd.read_csv(gd_path(files_id["publishers"]), sep=";")
titles = pd.read_csv(gd_path(files_id["titles"]), sep=";")
employee = pd.read_csv(gd_path(files_id["employee"]), sep=";")

## 1. From how many different states are our authors?

In [3]:
authors['state'].unique()

array(['CA', 'KS', 'TN', 'OR', 'MI', 'IN', 'MD', 'UT'], dtype=object)

In [2]:
authors['state'].nunique()

8

### Hint:

In SQL the syntax is:

```sql
SELECT COUNT(DISTINCT state)
FROM authors;
```

## 2. How many publishers are based in the USA?

In [ ]:
publishers.loc[publishers['country']=='USA', ['pub_id']].nunique()

pub_id    6
dtype: int64

In [11]:
publishers.loc[publishers['country'] == 'USA', :]["pub_id"].count()

6

In [12]:
len(publishers[publishers['country'] == 'USA'])

6

### Hint:

In SQL the syntax is:

```sql
SELECT  COUNT(pub_id)
FROM publishers
WHERE country ="USA" ;
```

## 3. What's the average quantity of titles sold per sale by store 7131?

In [ ]:
sales.loc[sales['stor_id'] == 7131, ['qty']].mean()

qty    21.666667
dtype: float64

In [13]:
sales[sales["stor_id"] == 7131]["qty"].mean()

21.666666666666668

### Hint:

In SQL the syntax is:

```sql
SELECT AVG(qty)
FROM sales
WHERE stor_id=7131;
```

## 4. When was the employee with the highest level hired?

In [6]:
employee.nlargest(1, "job_lvl")['hire_date']

26    1989-03-01 00:00:00
Name: hire_date, dtype: object

In [5]:
employee.nlargest(1, "job_lvl")[['hire_date']]

              hire_date
26  1989-03-01 00:00:00

In [7]:
employee.sort_values(by='job_lvl',ascending=False).head(1)

,emp_id,fname,minit,lname,job_id,job_lvl,pub_id,hire_date
26,MJP25939M,Maria,J,Pontes,5,246,1756,1989-03-01 00:00:00

### Hint:

In SQL the syntax is:

```sql
SELECT hire_date
FROM employee
ORDER BY job_lvl DESC
LIMIT 1;
```

## 5. What's the average price of psychology books?

In [ ]:
titles.loc[titles['type']=='psychology', ['price']].mean()

price    13.504
dtype: float64

### Hint:

In SQL the syntax is:

```sql
SELECT AVG(price)
FROM titles
WHERE type = "psychology";
```

## 6. Which category of books has had more year-to-date sales, "business" or "popular_comp"? You can write two queries to answer this question.

In [ ]:
business_ytd_sales_total = titles.loc[titles['type']=='business', ['ytd_sales']].sum()

p_comp_ytd_sales_total = titles.loc[titles['type']=='popular_comp', ['ytd_sales']].sum()

print(f"Business books year to date sales are {business_ytd_sales_total[0]}")
print(f"Popular Computing books year to date sales are {p_comp_ytd_sales_total[0]}")

Business books year to date sales are 30788
Popular Computing books year to date sales are 12875

### Hint:

In SQL the syntax is:

```sql
SELECT SUM(ytd_sales), type
FROM titles
WHERE type = "business";
```

### Hint:

In SQL the syntax is:

```sql
SELECT SUM(ytd_sales), type
FROM titles
WHERE type = "popular_comp";
```

## 7. What's the title and the price of the most expensive book?

In [8]:
titles.nlargest(1, "price")[["title", "price"]]

                      title  price
7  But Is It User Friendly?  22.95

In [ ]:
titles.nlargest(1, "price").loc[:, ['title', 'price']]

                      title  price
7  But Is It User Friendly?  22.95

In [9]:
titles[["title", "price"]].sort_values("price", ascending=False).head(1)

                      title  price
7  But Is It User Friendly?  22.95

### Hint:

In SQL the syntax is:

```sql
SELECT title, price
FROM titles
ORDER BY price DESC
LIMIT 1;
```

## 8. What's the price of the most expensive psychology book?

In [ ]:
titles.loc[titles['type']=='psychology', ['price']].max()

price    21.59
dtype: float64

In [10]:
titles[titles['type'] == 'psychology'].sort_values(by='price', ascending=False).head(1)[['title', 'price']]

                                                title  price
10  Computer Phobic AND Non-Phobic Individuals: Be...  21.59

### Hint:

In SQL the syntax is:

```sql
SELECT MAX(price)
FROM titles
WHERE type = "psychology";
```

## 9. How many authors live in either San Jose or Salt Lake City

In [ ]:
authors.loc[(authors['city']=='San Jose') | (authors['city']=='Salt Lake City'), ['au_id']].count()

au_id    3
dtype: int64

### Hint:

In SQL the syntax is:

```sql
SELECT COUNT(au_id)
FROM authors
WHERE (city = "San Jose"
OR city = "Salt Lake City");
```